### ISSUE TITLE
Empower Gray Matter structure

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#219]
I'd like to improve Gray Matter structure and give it some more power to redefine some backed-in properties of base layout.

As a side effect, it will resolve #175.

Right now usually we deal with following Gray Matter. I've took Blog page Matter as an example, since it usually feature more properties than usually other pages do, so it will give better understanding:

```yaml
---
title:           Example article
breadcrumbTitle: Example article
contentTitle:    Example article
navTitle:        Example article
metaDesc:        Example article generated with %(company)s
shortDesc:       Example article generated with %(company)s. Wanna more?
author:          LotusTM
date:            2015-10-12T14:48:00

class:            'p-blog'
applyWrapper:     true
showContentTitle: true
showBreadcrumb:   true
showSidebar:      false
```

Though, for most pages it is enough to have those mandatory properties:

```yaml
---
title:           Example article
breadcrumbTitle: Example article
contentTitle:    Example article
navTitle:        Example article
metaDesc:        Example article generated with %(company)s
```

I'm thinking to change structure as follows. Note that it will now include all possible for Gray Matter properties, so you could take picture of fully configured page, which uses a lot of overrides:

```yaml
---
title:
  header:     # <title>header title</title>, `title` before
  breadcrumb: # `breadcrumbTitle` before
  content:    # `contentTitle` before
  nav:        # `navTitle` before

meta:
  description: # named `metaDesc` before

  theme-color: # defined Android browser bar color
  viewport:    # defines how page zoom behaves on mobile devices

  og: # Facebook OG
    type:
    site_name:
    locale:
    url:
    title:
    description:
    image:

  twitter:
    card:
    site:
    creator:
    url:
    title:
    description:
    image:
    image_alt:

link:
  alternate: # <link rel='alternate' hreflang='en-US' href='https://example.com/en-US/mypage'>
    - hreflang:
      href:
    ...
  canonical: # <link rel='canonical' href='http://example.com/other-page/'>
    - {type your href here}
    ...

preview: # named `shortDesc` before
author:
date:

class:
applyWrapper:
showContentTitle:
showBreadcrumb:
showSidebar:
```

As you can see, it finally allows to redefine Facebook OG and Twitter values for each page, whenever you need it, provide custom viewport and theme color, and even add additional alternate urls (Kotsu already generates them for you, but you might need to specify your own), or specify canonical urls list.

Though, I hesitate about new structure and wonder are some introduced renames good enough,

Regarding structure, I also have alternative version, where `meta` and `link` properties are flattened to root level. This makes dot notation calls shorter (typing `page.meta.og.site_name` can be quite annoying), but I'm not sure doesn't it introduce any issues.

For instance, `description` property falls into root and it might be unclear that it's one of meta descriptions. I can imagine someone might want to put into `description` desc of his page, not realizing that it's actually a meta description which should be not longer than 140 chars.

From another perspective, properties like `theme-color` or `viewport` placed under `meta` slightly bothers me too, since while technically they are `<meta>`, on practice for some people it might be not obvious that those properties should be placed under meta, since usually we assume under meta some metaphoric description, tiles, etc, but not those technical values. Yeap, despite it's false assumption.

I also slightly dislike that everything in root, but `title` has nesting.

Anyway, here it is:

```yaml
---
title:
  header:     # <title>header title</title>, `title` before
  breadcrumb: # `breadcrumbTitle` before
  content:    # `contentTitle` before
  nav:        # `navTitle` before

description: # named `metaDesc` before

theme-color: # defined Android browser bar color
viewport:    # defines how page zoom behaves on mobile devices

og: # Facebook OG
  type:
  site_name:
  locale:
  url:
  title:
  description:
  image:

twitter:
  card:
  site:
  creator:
  url:
  title:
  description:
  image:
  image_alt:

alternate: # <link rel='alternate' hreflang='en-US' href='https://example.com/en-US/mypage'>
  - hreflang:
    href:
  ...
canonical: # <link rel='canonical' href='http://example.com/other-page/'>
  - {type your href here}
  ...

preview: # named `shortDesc` before
author:
date:

class:
applyWrapper:
showContentTitle:
showBreadcrumb:
showSidebar:
```

To show some real examples, here are properties which most likely be used on Blog pages. Overriding of other properties is very rare case.

Was:

```yaml
---
title:           Example article
breadcrumbTitle: Example article
contentTitle:    Example article
navTitle:        Example article
metaDesc:        Example article generated with %(company)s
shortDesc:       Example article generated with %(company)s. Wanna more?
author:          LotusTM
date:            2015-10-12T14:48:00

class:            'p-blog'
applyWrapper:     true
showContentTitle: true
showBreadcrumb:   true
showSidebar:      false
```

Became:

```yaml
---
title:
  header:     Example article generated with %(company)s
  breadcrumb: Example article generated with %(company)s
  content:    Example article generated with %(company)s
  nav:        Example article generated with %(company)s

meta:
  description: Example article generated with %(company)s

  theme-color: 'red'

  og:
    type: 'article'
    image: /pathto/img.png

  twitter:
    image: /pathto/img.png

link: # to be hones, this is rare case, but can happen
  canonical:
    - /myotherpage/
    - /anotherpage/

preview: Example article generated with %(company)s. Wanna more?
author: LotusTM
date: 2015-10-12T14

class: 'p-blog'
```

Or with flatten structure:

```yaml
---
title:
  header:     Example article generated with %(company)s
  breadcrumb: Example article generated with %(company)s
  content:    Example article generated with %(company)s
  nav:        Example article generated with %(company)s

description: Example article generated with %(company)s

theme-color: 'red'

og:
  type: 'article'
  image: /pathto/img.png

twitter:
  image: /pathto/img.png

canonical:
  - /myotherpage/
  - /anotherpage/

preview: Example article generated with %(company)s. Wanna more?
author: LotusTM
date: 2015-10-12T14

class: 'p-blog'
```

But on most common pages we will see

```yaml
---
title:
  header:     Example article generated with %(company)s
  breadcrumb: Example article generated with %(company)s
  content:    Example article generated with %(company)s
  nav:        Example article generated with %(company)s

meta:
  description: Example article generated with %(company)s

class: 'p-somepage'
```

Note how stupid `meta.description` looks here... lonely property.

It would be not that lonely if we move `title.header` to `meta.title`, but it breaks our pattern of specifying all titles in one place:

```yaml
---
title:
  breadcrumb: Example article generated with %(company)s
  content:    Example article generated with %(company)s
  nav:        Example article generated with %(company)s

meta:
  title:       Example article generated with %(company)s
  description: Example article generated with %(company)s

class: 'p-somepage'
```

Or whole thing flatten

```yaml
---
title:
  header:     Example article generated with %(company)s
  breadcrumb: Example article generated with %(company)s
  content:    Example article generated with %(company)s
  nav:        Example article generated with %(company)s

description: Example article generated with %(company)s

class: 'p-somepage'
```

Note that we might periodically have on pages some technical or UI related properties, like:

```yaml
class:            'p-blog'
applyWrapper:     true
showContentTitle: true
showBreadcrumb:   true
showSidebar:      false
```

Those control UI displaying. The usually appear on Index page, or any other page, which might have unique layout, but shares most parts of base layout. For instance, some landing pages.

Or we might have some other technical properties, like

```yaml
generatorsBrands:
  - SomeCompany

generatorsTags:
  - cool-stuff
```

or

```yaml
generatorId: 55443
```

But I do not see anything better than placing them directly in root of Gray Matter, unless there are some good proposals.

**Comment by mrhyde** [comment]
I think we should simplify things, not complicate them. As result introducing all these changes without clear and defined benefits "smells fishy" to me.

For example. 
1) Taking into consideration that in most cases all titles are the same, why won't we use root property in that case? And if you really need to set some titles to a different value - just set those specific ones and fallback rest to default.
I can see that as something like:
```yml
title: Example article generated with %(company)s
# implies that we need to check type of title

# or

title:
  default: Example article generated with %(company)s
  nav: Example
# and rest will just set to default
```

Both cases will minimize amount of duplication.

2) Why are we bothering with defining all possible cases for meta tags if we can simply provide a simple interface to set any type of them from the page? Let them set any meta they want and just loop thru them and set the value (except some tricky cases of course).
We can even create a component that will do this for us and isolate it from a layout.

3) Custom data values should not fall into root object so we can identify them (separation of concerns). As for a name, it could be something like `data` or `custom` or `props`

**Comment by ArmorDarks** [comment]
1. On practice, in most cases those titles will be different with some very minor exceptions. It's especially often scenario when `navTitle` and `breadcrumbTitle` are radically different from other titles. So doing this only for few titles and not often occurring cases seems to me unreasonable and <kbd>CTRL+D</kbd> does the job perfectly.

   Though, merging isn't difficult to do (though, it will complicate further code of base layout), I'm not sure that it's justified on true projects. Kotsu isn't good example, since it's using mostly demo titles.

2. Unfortunately that won't work that easily, because some metas might require additional properties, or have specific format for value. For instance, Facebook OG uses `<meta property='og:type'>`, while Twitter uses `<meta name='twitter:card'>`. Note `property` and `name` difference.

   To handle all those cases we have to know what user wanted in foreahand, to proccess his input properly, or construct much more complicated interface in quite futile attempt supporting all those differences. Not to mention that in last case input for user won't be that elegant.

   However, in any case, we still have to decide where such properties should be declared. In root? In `meta`?

3. Maybe yes, but I still don't see good name. And it doesn't sound like important thing unless we're going to iterate upon those properties for some reason.

   We should also not forget that Gray Matter provide context for _this_ page, thus for some cases it is logical to put properties into root, so it's ends up as `page.someValue`.

**Comment by mrhyde** [comment]
1. We should think some more on this.
2. On this also. `meta` is perfectly clear candidate
3. Why not `page.data.__` then? You won't confuse it with page properties since it's clearly states `page data`

**Comment by ArmorDarks** [comment]
Significant part of this issue has been accomplished.

Unfortunately, because I didn't come to conclusion regarding titles structure (a lot of questions and nuances), it remained unchanged.

Current structure looks like this:

```yaml
---
url: # rarely used to override displayed url of page
breadcrumb: # rarely used to override page's breadcrumb
  - {segments}

title:
breadcrumbTitle:
contentTitle:
navTitle:

description: # meta description

themeColor: # defined Android browser bar color

og: # Facebook OG
  type:
  site_name:
  locale:
  url:
  title:
  description:
  image:

twitter:
  card:
  site:
  creator:
  url:
  title:
  description:
  image:
  image:alt:

alternate: # <link rel='alternate' hreflang='en-US' href='https://example.com/en-US/mypage'>
  - locale:
    url:
  ...
canonical: # <link rel='canonical' href='http://example.com/other-page/'>
  - {url}
  ...

image: # generic image, associated with page. Can be used by other pages to generate cards. Passed as value to Open Graph and Twitter meta data, unless for them already specified images
excerpt: # short summary of page, used mostly for blog posts
author:
date:

class:
bodyClass:
applyWrapper:
showContentTitle:
showBreadcrumb:
showSidebar:
```

**Comment by ArmorDarks** [comment]
What remained in this issue: decide __how to deal with titles structure__ and __decide what to do with other page-related data__


So far we have following variants:

* Current

   ```yaml
   ---
   url:              /

   title:            Title
   breadcrumbTitle:  Title
   contentTitle:     Title
   navTitle:         Title

   description:      Page description

   class:            p-index
   applyWrapper:     false
   showSidebar:      true
   showContentTitle: false
   showBreadcrumb:   false
   ```

* Nested titles

   ```yaml
   ---
   url: /

   title:
     page:       Title
     breadcrumb: Title
     content:    Title
     nav:        Title

   description: Page description

   class:            p-index
   applyWrapper:     false
   showSidebar:      true
   showContentTitle: false
   showBreadcrumb:   false
   ```

* Nested titles with defaults

   ```yaml
   ---
   url: /

   title: Title # implies that we need to check type of title

   description: Page description

   class:            p-index
   applyWrapper:     false
   showSidebar:      true
   showContentTitle: false
   showBreadcrumb:   false
   ```

   or

   ```yaml
   ---
   url: /

   title:
     default: Title
     nav: Example
     # and rest will just set to default

   description: Page description

   class:            p-index
   applyWrapper:     false
   showSidebar:      true
   showContentTitle: false
   showBreadcrumb:   false
   ```

* Completely Restructured data

   ```yaml
   ---
   url: /

   title: Title

   content:
     title:
       value: Title
       show: false

   breadcrumb:
     title: Title
     show: false

   nav:
     title: Title

   description: Page description

   wrappers:
     main: false

   sidebar:
     show: true
   ```
