### ISSUE TITLE
i18n of database

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#48]
We need to have way to work with i18n databases too.

Resource for some thoughts: https://github.com/TAPevents/tap-i18n-db

**Comment by ArmorDarks** [comment]
Seems that issue isn't that simple.

Sometimes we need to store something not just in templates or script, but in database. For example, products with their specs, user entries, etc.

Some of their properties might need l10n.

### What's the problem, Doc?

We can't (or to be more correct — shouldn't) `gettext` database queries like that:

``` javascript
gettext(database.entry)
```

Reasons:

* Extractors won't be able to get actual content of `database.entry`
* Even if first issue will be beaten (and it's possible by rendering, let's say, Nunjucks to html and getting text from there), we can't locolize in such way whole database — if some property won't be called with `gettext`, it will be never localized
* We can't serve `gettext`ed translations via API, since database actually never mutaded with new translations. We can map this somehow... but it doesn't look like right way of doing things

### So, what of that, pal?

So far the only reasonable way seems to hold l10n right inside database entries. It will look like this:

``` yaml
---
product:
  property1:
    _origin: text string # this string will be used for `baseLocale`
    _de-DE: Zeichenfolge
    _uk-UA: строка тексту
    _ru: строка текста # will match `ru-RU` and `ru-UA`
  subproperty:
    property2:
      _origin: text string 2
      _de-DE: Zeichenfolge 2
      _uk-UA: строка тексту 2
      _ru: строка текста 2
  plurals:
    apple:
      _origin: # array tells to function that it should be handled as plurals, like `ngettext`
        - %(count) apple
        - %(count) apples
      _de-DE:
        - %(count) Apfel
        - %(count) Äpfel
      _uk-UA:
        - %(count) яблуко
        - %(count) яблука
        - %(count) яблук
      _ru:
        - %(count) яблоко
        - %(count) яблока
        - %(count) яблок
```

To access such data we will need special functions:

* Get data for current locale:

  `tap(data.product.property1)` -> `text string`

* Get data for specicif locale:

  `dtap('de-DE', data.product.property1)` -> `Zeichenfolge`

* Get plural data for specific locale:

  `dntap('de-DE', data.product.plurals.apple, 2, 2)` -> `2 Äpfel`

Pros:

* Database can be actually localized
* It's easy to get data from
* It can handle plurals

Cons:

* We can't send it to translation platforms in such forms, and there is no easy way to extract messages for translation — probably we'll need parser for it. Or handle it manually (which will be possible only with small database)
* Even if we'll manage to extract messages for translation, we will have to find way to dump it back into database in appropriate form
* To serve such database as API, it have to be mutated (`API/get/product/en` should return us only English strings, instead of all). But I think it isn't big issue. Example: http://www.drzon.net/approaches-to-json-internationalisation-i18n/
* A lot of l10n-related properties cluttering database and makes it harder to read.
* And worst from all to me — we're introducing whole new layers, making thinks inconsistent by using `gettext` for strings, and `tap` (or whatever name it will get) for accessing database quries, which require different handling, different way of extraction, etc.

### Kind of bonus

Just to mention, [tap-i18n-db](https://github.com/TAPevents/tap-i18n-db) uses similar approach, but a bit different structure:

``` yaml
---
product:
  property1: text string # this string will be used for `baseLocale`
  subproperty:
    property2: text string 2
  plurals:
    apple:
      - %(count) apple
      - %(count) apples
  i18n:
    property1:
      de-DE: Zeichenfolge
      uk-UA: строка тексту
      ru: строка текста
    subproperty:
      property2:
        de-DE: Zeichenfolge 2
        uk-UA: строка тексту 2
        ru: строка текста 2
    plurals:
      apple:
        de-DE:
          - %(count) Apfel
          - %(count) Äpfel
        uk-UA:
          - %(count) яблуко
          - %(count) яблука
          - %(count) яблук
        ru:
          - %(count) яблоко
          - %(count) яблока
          - %(count) яблок
```

But it works pretty much the same, as described above example.

Pros:

* Much cleaner original object

Cons:

* No way to mark which strings should be translatable (thus, which one should be extracted and sent to translation platform)

  I guess that approach assumes, that whole database should be translatable.

  However, entries, which have 100-200 properties, from which only 1-2 should be translatable, looks like problematic to me...

* Duplication of structure, which makes harder to maintain YAML or JSON-based manually managed databases

**Comment by ArmorDarks** [comment]
Some insane idea struck my head. What if we could do it like this?

``` yml
---
product:
  property1: {{ gettext('text string') }}
  subproperty:
    property2: {{ gettext('text string 2') }}
    partial: string where only {{ gettext('some part') }} translatable
  plurals:
    apple: {{ ngettext('%(count)s apple', '%(count)s apples', %(count)s, %(count)s) }}
```

It so crazy, that actually might work!

For getting data from such database we'll need special functions:

* Get data for current locale:

  `dbgettext(data.product.property1)` -> `text string`

* Get data for specicif locale:

  `dbdgettext('de-DE', data.product.property1)` -> `Zeichenfolge`

* Get plural data for specific locale:

  `dbdngettext('de-DE', data.product.plurals.apple, 2, 2)` -> `2 Äpfel`

Those are, in fact, very similar to original `gettext` functions, but they will:

1. Forcefully render Nunjucks template inside
2. Pass into inner `gettext` function arguments (just remapping, nothing more)
3. By rendering Nunjucks template execute inner `gettext` function
4. Return whole property with backed-in translation

Props:

* Clean original database, without tons of nested properties in forms of locales
* Single i18n way for database and for templates
* `gettext` inside database in theory can be extracted by any parser (for example, in JavaScript mode)
* Translators will receive strings from such database in form of ordinary `.po` file, so they even won't realize that they're working with database translation
* Extractors will merge all duplicates of strings, unless `context` will be provided

* Cons:

* So far I don't see possibility to use more than one `gettext` in single property, otherwise it won't be possible to decide to which inner `gettext` should be mapped `dbgettext` arguments. Though, probably it's solvable
* A bit unordinary database
* No way of retrieving data from such database without special functions
* For external API it should be somehow pre-rendered, which is kind of not what you'd expect from `yaml` and `json` files

**Comment by mrhyde** [comment]
And how are you planning to do selects/filter/map from this kind of data? :)

**Comment by mrhyde** [comment]
More specific example - search

**Comment by ArmorDarks** [comment]
Pre-render it? :) So far I don't know, it's just an idea.

**Comment by ArmorDarks** [comment]
Okey, some thoughts about "crazy" approach.

First of all, I've tried to use `{{ gettext('String') }}` right inside yaml files and then render those data-files into temporary folder, from which Nunjucks and other modules can grab it.

Some significant cons:

1. You're stuck with data-files only — you can't render in such way, for example. data, specified right inside Gruntfile. However, it's solvable by importing gettext functions inside Gruntfile
2. You have to generate new data file for each locale
3. On change of any data file, you will kick-off Grunt's regeneration of data files and templates... it results in quite a lot of generations, and they aren't quick
4. You have to put extra tasks inside `grunt` and `grunt:build` to generate data actually before it will be passed anywhere, since you're requiring it inside Gruntfile... it's end up quite unclear what happening

Pros:

* You receive prepared and localized data, nothing extra should be done to work with it

Then I've tried another, "live" method.

Instead of pre-generating data with Nunjucks via Grunt, I've tried to do it in "live" mode. We'll just use function, which takes passed in query and renders it with Nunjucks:

``` coffee
###*
 * Render `gettext` function inside of database query result
 * @param {object} query                  Object to render and invoke it's `gettext` functions
 * @param {string} locale = currentLocale Locale, from which string should be loaded
 * @return {string|object} Localized result
###
env.addGlobal 'dbgettext', (query, locale = currentLocale) ->
  if locale != currentLocale
    @.ctx.page.locale    = locale
    @.ctx.page.isoLocale = isoLocale(locale)
    @.ctx.page.language  = getLangcode(locale)
    @.ctx.page.region    = getRegioncode(locale)
  # Stfingify object in case we have not single property
  query = JSON.stringify(query)
  # @note Handle cases, when value starts with `{`, otherwise `JSON.stringify()` will
  #       transform them into inner object
  # @note Handle cases, when we have escaped single quotes inside — we need to enforce
  #       proper escaping for Nunjucks render
  query = query.replace(/\={{/gm, '{{').replace(/\\\\\'/gm, '\\\'')
  rendered = new nunjucks.Template(query).render(@)
  JSON.parse(rendered)
```

then we can do it like that:

our database (`company`):

``` yml
---
type: null
typeFull: null
name: Name
nameFull: Full name
abr: String {{ gettext('gettext string') }}
abrE: ={{ gettext('ge"ttext \'string') }}
details: null {{ test + 32 }}
personnel:
  -
    position: Person
    name:
      first: Name
      last: Last
    photo: null
```

And our templates:

``` jinja
{% set rendered = dbgettext(company) %}
{% set renderedLocaleSpecific = dbgettext(company, 'ru-UA') %}

<h5>Original from db:</h1>
<p>{{ company.abr }}</p>
<h5>dbgettext from db:</h1>
<p>{{ dbgettext(company.abr) }}</p>
<h5>From `rendered`:</h1>
<p>{{ rendered.abr }}</p>
<h5>From `rendered` with escaping:</h1>
<p>{{ rendered.abrE }}</p>
<h5>From `renderedLocaleSpecific`:</h1>
<p>{{ renderedLocaleSpecific.abr }}</p>

<br>

<h5>Original from gruntfile:</h1>
<p>{{ site.twitter }}</p>
<h5>dbgettext from gruntfile:</h1>
<p>{{ dbgettext(site.twitter) }}</p>

Redefine data with rendered one
{% set company = dbgettext(company) %}

<br>

<h5>From redefined db:</h1>
<p>{{ company.abr }}</p>
```

Will give us some nice results:

*note: render with specific locale returns English strings, since I didn't add translated strings yet. Will test it out later*

![2015-10-30_14-20-05](https://cloud.githubusercontent.com/assets/4460311/10845553/7037ed20-7f11-11e5-9bb8-98cabe38cb2c.png)

Some caveats:

* You can't write in database like that:

  ``` yml
  ---
  abrE: {{ gettext('ge"ttext \'string') }}
  ```

  `JSON.stringify()` will thinks it's two inner object and result in improper object for render

  That's why I've implemented small hack with leading `=` which will enforce proper stringification.

* So far you can't use double quotes:

  ``` yml
  ---
  abrE: ={{ gettext("gettext string") }}
  ```

  Because it will result in escaped quotes in function `gettext(\"gettext string\")`, and Nunjucks will throw and error into you

  Can be solved by some tricky regex search and replace

**Comment by ArmorDarks** [comment]
Just for consideration, we can also render all databases during `preprocessData` of `grunt-nunjucks-2-html`

It will end up like:

``` yml
---
# `currentLocale` in root
data: 1
company: Test
ru-UA:
	data: 1
	company: Тест
uk-UA:
	data: 1
	company: Тест
```

Pres:

* All data already generated, you can access it without any functions, just like `data.company` for current locale or `data['ru-UA'].company` for specific

Cons:

* Generated data will be available only in Nunjucks. We still will need to generate it separately to be shareable across other modules. But in most cases Nunjucks is top-consumer of data.
* Multiplication of data. With 3 locales — 3x size, with 20 - 20x size. Not an issue in our case, but still doesn't sound good

So far I think it's better to render data on demand with special functions, like `dbgettext()`.

**Comment by ArmorDarks** [comment]
Okey, continuing researching. Let's back to our variant with generated db queries in live on demand.

Actually, what we need to make it full i18n implementation for databases?

1. Output single standalone string, or mixed with texts, into current locale
2. Output string with specific context
3. Output string from specific domain (file in our case)
4. Output string into specific locale
5. Placeholders
6. Output plural strings



## 1. Ordinary strings

Outputting of standalone or mixed strings works majestically. There is nothing special about it:

``` yml
---
property:
  subproperty: ={{ gettext('My string 1') }}
  subpropert2: Mixed with `{{ gettext('My string 1') }}` string 2
```

``` coffee
dbgettext(property.subproperty) # -> 'Моя строка'
dbgettext(property.subproperty2) # -> 'Змішана з `Моя строка 1` строка 2'
```



## 2. Around context

Outputting of strings with specific context will work just fine too:

``` yml
---
property:
  subproperty: ={{ pgettext('text', 'My string') }}
  subproperty2: ={{ pgettext('something else', 'My string') }}
```

``` coffee
dbgettext(property.subproperty) # -> 'Моя строка'
dbgettext(property.subproperty2) # -> 'Моя строка, але інша'
```

It works and doesn't require any additional efforts, since we define context inside our property, and there is no situations when you'd like to redefine context from calling `dbgettext()` function. And you shouldn't do that.



## 3. Into someone's domain

Outputting of string from specific domain will work too:

``` yml
---
property:
  subproperty: ={{ dgettext(':navbar', 'My string') }}
  subproperty2: ={{ dgettext(':article', 'My string') }}
```

``` coffee
dbgettext(property.subproperty) # -> 'Моя строка'
dbgettext(property.subproperty2) # -> 'Моя строка, але інша'
```

We don't have and shouldn't redefine domain from outer calling function `dbgettext()`, so there is no problems with it.

Since `node-gettext` uses domain in a bit inordinary manner (see details here https://github.com/andris9/node-gettext/issues/24), we're using a bit tricky domains-access implementation, described here: https://github.com/LotusTM/Kotsu/commit/c0f1ec0f001120c6b707a6de29b36269027f8cc1

In example above used a bit enhanced version, which treats leading `:` as "look for that domain in current locale"



## 4. I wanted to say `Sprechen Sie Deutsch?`

When we're coming to outputting of strings into specific locale... it becomes a bit worse.

First of all, there is no way for us to control in which language will be outputted `gettext()`, `ngettext()` and `pgettext()`. They're always working with "current locale", which defined in Grunt task during task run.

To enforce outputting of specific locale, we have to use their domain-controlling equivalent, like `dgettext()` or `dngettext()`.

At first glance there is nothing wrong with it:

``` yml
---
property:
  subproperty:  ={{ dgettext('en-US', 'My string') }}
  subproperty2: ={{ dgettext('uk-UA', 'My string') }}
```

``` coffee
dbgettext(property.subproperty) # -> 'My string'
dbgettext(property.subproperty2) # -> 'Моя строка'
```

That works just fine when we need to have inside our property always translated into specific locale string. You might need it, for example, in such case:

``` yml
---
property:
  subproperty: Remember, that 'My string' in `uk-UA` should be translated as {{ dgettext('uk-UA', 'My string') }}
```

But wait... what if we need to output other, not bound to specific locales strings, into another locale?

In other words, we won't face that issue during generation of database for current locale, but it comes into play when we need to output string from specific locale in another locale on demand in view.

For instance, this won't work:

``` coffee
'Some english text with `uk-UA` string insde: ' + dbdgettext('uk-UA', property.subproperty)
```

Because we have not domain-specific functions inside our property. So, looks like we have to use *always* domain specific locales in database, but it will be messy anyway:

``` yml
---
property:
  subproperty: ={{ dgettext(currentLocale, 'My string') }}
  subproperty2: ={{ dgettext(currentLocale, 'My string') }}
```

Not only we'll have to write much longer `dgettext` functions inside our database with additional argument, it's unclear where `currentLocale` variable should come for. It doesn't exist, and we have to create it in context before rendering database with Nunjucks.

By doing this such way, though, we actually can redefine current locale from `dbgettext()` function:

``` coffee
env.addGlobal 'dbdgettext', (query, locale = currentLocale) ->
  # get context of Nunjucks current environment, which includes whole database
  context = @.getVariables()
  context = _.clone(context)
  # This is where magic happens
  if locale != currentLocale
    context.currentLocale = locale
  # render our query
  # ...
```

But writing full `dgettext()` in database properties for no reason (since all regular functions, not bound to specific locale, must be outputable in any locale any time) seems wrong to me.

So far I don't see good solution for it, but this might work:

``` yml
---
property:
  subproperty: ={{ gettext('My string') }}
  subproperty2: ={{ gettext('My string') }}
```

``` coffee
env.addGlobal 'dbdgettext', (query, locale = currentLocale) ->
  context = @.getVariables()
  context = _.clone(context)
  tempLocaleName = 'tempGettextLocale'
  # This is where magic happens
  context[tempLocaleName] = locale
  query = JSON.stringify(query)
  # This is where magic happens second time.
  # Replace all regular `gettext()` function with domain-specific functions and our temporary locale
  query = query
    .replace(/gettext(/gm, 'dgettext(' + tempLocaleName + ', ')
    .replace(/ngettext(/gm, 'dngettext(' + tempLocaleName + ', ')
  # ... and other functions ...
  # continue on preparations and render our query
  # ...
```

So that magically will end up working:

``` coffee
'Some english text with `uk-UA` string insde: ' + dbdgettext('uk-UA', property.subproperty) # -> 'Some english text with `uk-UA` string insde: Моя строка'
```

The bad side of it that it looks like some kind of black magic, a hack rather then solution... but it works...



## 5. Hey guys, can you hold that place for me for a minute?

So, the more we're coming to the end, the worse becomes things, aren't they? :) Probably this might indicate that my solution was fault at first place and corrupted in it's nature. *But temptation to use single solution for templates, JavaScript and database is so powerful!..*. Shhh. Shut up!

On the other hand, it might be me who doesn't see obvious and elegant solution.

What we have now? Placeholders... Situation with placeholder is quite nasty.

First of all, there are two scenarios, when we need to use placeholders:

1. Static value, which should be pulled into string from somewhere else.
  
  For example, `company.name`, or `site.name` — those values actually existing in our database, but sometimes you need to pull them into another string, like this:

  ``` yml
  ---
  propety: This is %(company)s site
  ```

2. Dynamic values.

  Sometimes we can fill placeholder only when we actually know value, which should be there. And we can't get that value before we'll have needed data for it.

  ``` yml
  ---
  propety: This is %(username)s, his color is %(color)s
  apples: You have %s apples
  ```

  We can't fulfil those placeholders with anything, unless we have clear context.

Okey, so, why do we care?

It becomes very important during database rendering, because you suddenly realize that *you can't just render database with placeholders*, because values for those placeholders are unknown. You will end up with:

``` yml
---
propety1: ={{ gettext('This is %(sitename)s') }} # will throw error about non-existing placeholder
propety2: ={{ gettext('This is %(username)s, his color is %(color)s') }} # will throw error about non-existing placeholders
apples: ={{ gettext('You have %s apples') }} # will return `You have undefined apples`
```

You can't pass in placeholder like that:

``` coffee
dbgettext(subproperty1, { sitename: site.name })                       # case 1
dbgettext(subproperty2, { username: result.user. color: result.colo }) # case 2
dbgettext(apples, result.count)                                        # case 3
```

Because `dbgettext()` can't pass placeholder as argument inside. And even if it's possible (and let's just say, that it's possible, but tricky and nasty), we'll face following issues anyway:

1. Case 1 will work in context of template, where you're calling `dbgettext()` with defined placeholder, but will fail in all other cases. Especially it's important during generation of database for API, or on page, which doesn't have defined `dbgettext()` with those placeholder. It will end up with undefined values. That's because for obvious reason our database can't know what do you want to place into that particular placeholder, unless you specify it
2. Cases 2 and 3 awaits same outcome. The only difference here, that we even can't predefine those values somewhere globally, because they're becoming know to us only during some specific operations

For case 1 we can develop some kind of workaround. For example, define `globalPlaceholder` object, which will hold all placeholders. Then we can pass it throw context and use just like that:


``` yml
---
propety1: ={{ gettext('This is %(sitename)s'), globalPlaceholder }}
```

Then you can pass in placeholder like that:

``` coffee
globalPlaceholder = {
  sitename: site.name
}

dbgettext(subproperty1)
```

So, you will have global placeholders everywhere in database, since it's the only way to define them in context-unaware environment. And, probably, will end up inventing some unclearly named placeholders to avoid collisions.

However, I think it can be completely simplified. Why use global placeholders, if in most cases we're calling back to database? And in context of database I think it shouldn't be made in other way. If we're passing to placeholders values, which database doesn't contain — we're screwed up.

So, it can be just like that:

``` yml
---
propety1: ={{ gettext('This is %(sitename)s'), sitename. site.name }}
```

``` coffee
dbgettext(property1) # -> 'This is kotsu'
```

Those properties rendered in context of Nunjucks, which upholds whole database, so it's completely fine. Nunjucks will serve as a kind of loophole from one property to another. And we don't need ability to redefine them from outer `dbgettext()` function, since "on going" operation shouldn't affect them, otherwise we won't be able to generate our database for serving in context-unaware environment.

But it doesn't solve case 2 and case 3.

Let's think. If property contains dynamic value, what should it return? 

If it's

``` yml
---
apples: ={{ gettext('You have %s apples') }}
```

There is no way for us to know how many apples there are to print unless we reach particular line in templates.

So, I think, in such cases `gettext('You have %s apples')` should return `'You have %s apples'`.

Yes, unprocessed placeholder, which we could process with `sprintf` in view, or where we need. It means, that generated database will uphold such strings with unprocessed placeholders, ready to spit it to us when we need it.

Of course, it's questionable what it should return for APi... but I think that unprocessed string in such case is completely ok too.

Must admit, that I can't say for now for whatever reason you might need to uphold such strings in database, but it's completely possible that they might appear at some point in future.

So far `sprintf` can't output unprocessed placeholders for undefined values (see details here: https://github.com/alexei/sprintf.js/issues/78). But, as usually, it's possible to preserve them with some voodoo magic and regex.



## 5. So how many apples do you say you have?

Okey, we're almost done. It was quite long and unpleasant journey. So far we done nothing but built workarounds and hacks. Will it dramatically change in last chapter?

Let's see.

Plurals is one of the most crucial feature of `gettext`

However, as soon as we try to use it in database — we're in trouble

``` yml
---
apples: ={{ ngettext('You have %s apple', 'You have %s apples', count, count) }}
```

Here comes into play at once few issues:

1. Dynamic values for placeholders — we can't have their values during generation of database
2. Wow, in fact we can't serve here even some string with unknown placeholders. — we can't know which one plural form to serve

Let's solve it one at once.

### 1. Dynamic values

Technically it seems to be similar to describe in previous chapter issue.

But it's more complex.

We need possibility to pass in those values from external source. in our case — outer `dbgettext()`, right during rendering needed content.

But this won't work:

``` coffee
# Let's imagine that we have special `plural` function — `dbngettext()`, like `ngettext`
dbngettext(apples, 2, 2)
```

This won't work, because there is no clear way to remap those values to inner `ngettext()` function.

Just to mention, we can't specify it as

``` yml
---
apples: ={{ ngettext('You have %s apple', 'You have %s apples', %(count)s, %(count)s) }}
```

Because when you will try to fill `%(count)s` with `sprintf`, function already will be rendered and invoked, so `ngettext` won't be able to choice anything

``` coffee
sprintf(
  dbngettext(apples), { count: 2 } # -> 'You have %(count)s apple'
) # -> 'You have 2 apple'
```

So you need to do it from outer to inner, which is impossible in that case

We can try to mix our previous approaches:

``` yml
---
apples: ={{ ngettext('You have %s apple', 'You have %s apples', count) }}
```

``` coffee
env.addGlobal 'dbngettext', (query) ->
  context = @.getVariables()
  context = _.clone(context)
  # This is where magic happens
  context.count = count
  # continue on preparations and render our query
  # ...
```

Then you can pass in placeholder like that:

``` coffee
result = dbngettext(apples, 2) # -> 'You have %s apples'
# and finalize with sprintf
sprintf(result, 2)             # -> 'You have 2 apples'
```

It will work, because `dbngettext` will pass on argument `count` as property into database context.

This seems to be ok, but once again — some kind of voodoo magic happening behind. For some reason we're specifying "magically appearing" `count` variable instead of `%(count)s` placeholder.

But wait... what if you will pass whole node of database inside function with defined `count`?

``` yml
---
list:
  apples: ={{ ngettext('You have %s apple', 'You have %s apples', count) }}
  sub:
    car: ={{ ngettext('You have %s car', 'You have %s cars', count) }}
```

``` coffee
sprintf(dbngettext(list, 2), 2)
```

will result it:

``` yml
---
list:
  apples: You have 2 apples
  sub:
    car: You have 2 cars
```

Oops... probably not what we expected...

But I guess it's improper to use function with specified `count` on nodes, unless you really want all `count` to be filled with provided value?

### 2. Plural forms and undefined placeholders

In case of undefined placeholders, we can't return here same string, because some language can have two plural forms, some — 3 or more.

So, what string we should return here? We can't just return `'You have %s apple'`, because then we might want to provide here 5 for placeholder, and... ops, it results in `'You have 5 apple'`

So, for cases, when we have unknown placeholders, we need to return array of possible values:

``` yml
---
apples: 
  - 'You have %s apple'
  - 'You have %s apples'
```

Then we could use [smartPlurals](https://github.com/scottrippey/Smart-Plurals) to select proper form based on count, and `sprintf` to fill placeholder with necessary value. I don't like involving of 3rd party utility for pluralization here, but I don't see another option so far.

In case we know placeholders values, we can return pluralized string as usually:

``` yml
---
apples: ={{ ngettext('You have %s apple', 'You have %s apples', 2, 2) }}
```

``` coffee
dbgettext(apples) # -> 'You have 2 apples'
```

But this have few caveats too:

1. Technically you can't have `ngettext()` template mixed with string, because script won't know where to fill in array in case of unknown placeholders. But it's only in case of unknown placeholder's value.

  But if you know those values right inside database — why do you even use `ngettext()`? Unless you need loophole to another database property with number...

2. `ngettext()` can't decide, what should it do — return array or localized string in case of unknown count or not.
  
  It's possible to solve by augmenting `ngettext()`:

  ``` coffee
  env.addGlobal 'ngettext', (string, stringPlural, count, placeholders...) ->
    if count
      # return usual `ngettext()`
    else
      # return array with possible values
  ```

3. It's a bit tricky to get all plural forms, but it's possible by accessing `node-gettext` plural rules for particular locale (see here: https://github.com/andris9/node-gettext/issues/25), or getting possible values from `gt.domains[*locale name*]...[*array with plural forms*]`



## Praise the Summarization!

What we have in the end?

1. Output single standalone string, or mixed with texts, into current locale

  Works, almost no tricks.

  Leading `=` or wrapping quotes for cases, when there it's not mixed with other strings

  ``` yml
  ---
  property1: With text {{ gettext('My string') }}
  property2: ={{ gettext('My string') }}
  property3: "{{ gettext('My string') }}"
  property4: '{{ gettext(\'My string\') }}'
  ```

  Inner double qoutes for arguments won't work — need some tricky regext to properly escape them:

  ``` yml
  ---
  property4: '{{ gettext("My string") }}' # won't work
  property4: '{{ gettext(\"My string\") }}' # won't work
  property4: "{{ gettext(\"My string\") }}" # won't work
  ```

2. Output string with specific context

  Just works, like regular strings. We don't need to redefine context in outer function.
 
3. Output string from specific domain (file in our case)

  Just works, like regular strings. We don't need to redefine domain in outer function
 
4. Output string into specific locale

  A bit of replacing regex, and redefining with outer function works:

  ``` yml
  ---
  property: ={{ gettext('My string') }}
  ```

  ``` coffee
  'Some english text with `uk-UA` string insde: ' + dbdgettext('uk-UA', property)
  ```

It will generate all non-language specific functions with specified language.

5. Placeholders

  You can predefine placeholders in database, using them as kind of loophole or micro-templating for accessing other database values:

  ``` yml
  ---
  propety1: ={{ gettext('This is %(sitename)s'), { sitename: site.name }}
  ```

  ``` coffee
  dbgettext(property1) # -> 'This is kotsu'
  ```

  But you can't define those placeholders elsewhere. On that point we're assuming that you would never do it.
  
  Undefined placeholders will be returned as they are, so you can template them with `sprintf` (`|template()` Nunjucks filter in Kotsu) in view:

  ``` yml
  ---
  propety1: ={{ gettext('This is %(sitename)s') }}
  ```

  ``` jinja
  {{ dbgettext(property1)|template({ sitename: 'My name' }) # -> 'This is My name' }}
  ```

  This is how you can define placeholders "on demand"

6. Output plural strings

  You need to use a bit "magic" `count` variable inside database property, which will pass on value from outer function `dbngettext()`:

  ``` yml
  ---
  apples: ={{ ngettext('You have %s apple', 'You have %s apples', count) }}
  ```

  ``` coffee
  dbngettext(apples, 2)|template(2) # -> 'You have %s apples'
  ```
 
 In case of undefined `count`, array of possible forms will be returned for further templating:

 ``` yml
 ---
 apples: 
   - 'You have %s apple'
   - 'You have %s apples'
 ```

 ``` jinja
 {{ apples|plural(2)|template(2) } # -> 'You have %s apples'
 ```

 * You can't have mixed `ngettext` with string inside single property, otherwise output might be unpredictable.
 * Only one `count` (and previous limitation) makes it impossible to use more then one `ngettext` in single property
 * Calling `dbngettext(database, 2)` with defined count will result in node, where every `count` will be filled with defined number, and `ngettext()` rendering according to that number
