### ISSUE TITLE
Replace scss-lint with stylelint

### ISSUE THREAD

**Issue by ArmorDarks** [LotusTM/Kotsu#57]
True magic happens, and non-Ruby dependent trending linter for Sass appears out of nowhere: http://stylelint.io/

**Comment by ArmorDarks** [comment]
Old SCSS-Lint config:

``` yml
linters:
  BangFormat:
    enabled: true
    space_before_bang: true
    space_after_bang: false

  BemDepth:
    enabled: true
    max_elements: 2

  BorderZero:
    enabled: true
    convention: zero # or `none`

  ColorKeyword:
    enabled: true

  ColorVariable:
    # @todo Temporary disabled due to large quantity of not fulfilling
    #       requirements color properties.
    #       Should be enabled in future
    enabled: false

  Comment:
    # @todo Temporary disabled due to some legacy sections which still have CSS comments
    enabled: false

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DisableLinterReason:
    enabled: false

  DuplicateProperty:
    enabled: true

  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  EmptyRule:
    enabled: false

  ExtendDirective:
    enabled: false

  FinalNewline:
    enabled: true
    present: false

  HexLength:
    enabled: true
    style: short # or 'long'

  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  HexValidation:
    enabled: true

  IdSelector:
    enabled: true

  ImportantRule:
    enabled: true

  ImportPath:
    enabled: true
    leading_underscore: false
    filename_extension: false

  Indentation:
    # @todo Disabled due to unexpected behaviour when intended variables with selectors
    #       treated as faulty
    #       Github issues: https://github.com/brigade/scss-lint/issues/617
    #                      https://github.com/brigade/scss-lint/issues/618
    enabled: false
    allow_non_nested_indentation: true
    character: space # or 'tab'
    width: 2

  LeadingZero:
    enabled: true
    style: exclude_zero # or 'include_zero'

  MergeableSelector:
    enabled: true
    force_nesting: true

  NameFormat:
    enabled: true
    allow_leading_underscore: true
    convention: '^[a-z]|-{3}|_{3}|[^_]_[^_]+$' # hyphenated_BEM regex pattern

  NestingDepth:
    enabled: true
    max_depth: 4
    ignore_parent_selectors: false

  PlaceholderInExtend:
    enabled: false

  PropertyCount:
    enabled: false
    include_nested: false
    max_properties: 10

  PropertySortOrder:
    # @todo Should be enabled when custom order will be completed
    enabled: false
    ignore_unspecified: false
    min_properties: 2
    separate_groups: true
    # @todo WIP
    order:

      # Position

      - position

      - top
      - right
      - bottom
      - left

      - float
      - clear

      # Display

      - display
      - flex
      - box-flex

      - box-sizing

      - overflow
      - overflow-x
      - overflow-y

      - clip

      - content

      - z-index
      - opacity
      - visibility

      # Tables

      - table-layout

      - border-collapse
      - border-spacing
      - empty-cells

      # Lists

      - list-style
      - list-style-type
      - list-style-position
      - list-style-image

      # Columns

      - columns
      - column-gap
      - column-fill
      - column-rule
      - column-span
      - column-count
      - column-width

      # Aligning

      - text-align
      - vertical-align

      - flex-basis
      - flex-direction
      - flex-flow
      - flex-grow
      - flex-shrink
      - flex-wrap
      - align-content
      - align-items
      - align-self
      - justify-content
      - order

      - box-align
      - box-orient
      - box-pack

      # Dimensions

      - width
      - min-width
      - max-height
      - height
      - min-height
      - max-width

      # Spacing

      - padding
      - padding-top
      - padding-right
      - padding-bottom
      - padding-left

      - margin-collapse
      - margin-top-collapse
      - margin-right-collapse
      - margin-bottom-collapse
      - margin-left-collapse

      - margin
      - margin-top
      - margin-right
      - margin-bottom
      - margin-left

      # Text wrapping

      - hyphens
      - text-overflow
      - text-wrap
      - white-space
      - word-break
      - word-wrap

      # Text

      - font-size
      - text-size-adjust
      - line-height

      - text-indent

      - letter-spacing
      - word-spacing

      - color

      - font
      - font-family
      - font-smoothing
      - text-rendering

      - font-variant
      - text-transform

      - font-style
      - font-weight
      - text-decoration

      - src

      # Background

      - background-size
      - background-clip
      - background
      - background-color
      - background-image
      - background-repeat
      - background-attachment
      - background-position

      # Borders

      - border-image

      - border
      - border-top
      - border-right
      - border-bottom
      - border-left
      - border-width
      - border-top-width
      - border-right-width
      - border-bottom-width
      - border-left-width
      - border-style
      - border-top-style
      - border-right-style
      - border-bottom-style
      - border-left-style
      - border-color
      - border-top-color
      - border-right-color
      - border-bottom-color
      - border-left-color

      - border-radius
      - border-radius-topright
      - border-top-right-radius
      - border-radius-bottomright
      - border-bottom-right-radius
      - border-radius-bottomleft
      - border-bottom-left-radius
      - border-radius-topleft
      - border-top-left-radius

      - outline
      - outline-width
      - outline-style
      - outline-color
      - outline-offset

      # Shadows

      - box-shadow
      - text-shadow

      # Animations, transitions, transforms

      - animation
      - animation-delay
      - animation-duration
      - animation-iteration-count
      - animation-name
      - animation-play-state
      - animation-timing-function
      - animation-fill-mode

      - transition
      - transition-delay
      - transition-duration
      - transition-property
      - transition-timing-function

      - transform

      # Cursor

      - pointer-events

      - cursor

      # Misc

      - quotes
      - filter
      - size
      - zoom
      - backface-visibility
      - resize
      - appearance
      - user-select
      - interpolation-mode
      - direction
      - marks
      - page
      - set-link-source
      - unicode-bidi
      - speak
      - caption-side

  PropertySpelling:
    enabled: true
    extra_properties: []

  PropertyUnits:
    enabled: true
    global: [
      'ch', 'em', 'ex', 'rem',                 # Font-relative lengths
      'cm', 'in', 'mm', 'pc', 'pt', 'px', 'q', # Absolute lengths
      'vh', 'vw', 'vmin', 'vmax',              # Viewport-percentage lengths
      'deg', 'grad', 'rad', 'turn',            # Angle
      'ms', 's',                               # Duration
      'Hz', 'kHz',                             # Frequency
      'dpi', 'dpcm', 'dppx',                   # Resolution
      '%']                                     # Other
    properties: {}

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 4

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM # or hyphenated_lowercase or 'snake_case', or 'camel_case', or a regex pattern

  Shorthand:
    enabled: true
    allowed_shorthands: [1, 2, 3]

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true
    style: at_least_one_space # or 'no_space', or 'one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceAfterVariableName:
    enabled: true

  SpaceAroundOperator:
    # @todo Temporary disabled, since it need option `at least one space`,
    #       otherwise variables can't be aligned properly
    #       Github issue: https://github.com/brigade/scss-lint/issues/615
    enabled: false
    style: one_space # or 'no_space'

  SpaceBeforeBrace:
    enabled: true
    style: space # or 'new_line'
    allow_single_line_padding: true

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolon:
    enabled: true

  TrailingWhitespace:
    enabled: true

  TrailingZero:
    enabled: true

  TransitionAll:
    enabled: false

  UnnecessaryMantissa:
    enabled: true

  UnnecessaryParentReference:
    enabled: true

  UrlFormat:
    enabled: true

  UrlQuotes:
    enabled: true

  VariableForProperty:
    enabled: false
    properties: []

  VendorPrefix:
    enabled: true
    identifier_list: base
    additional_identifiers: []
    excluded_identifiers: []

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
```
